FROM ubuntu:latest

ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -y update
RUN apt-get -y install git 
RUN apt-get -y install npm

RUN git clone https://github.com/AlexTraher/Socket.io-Messenger.git
WORKDIR Socket.io-Messenger
RUN npm install
