FROM ubuntu:latest

RUN apt-get -y update

RUN apt-get -y upgrade

RUN apt-get install -y build-essential

RUN apt-get install -y git

RUN cd ~

RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MIFT2021
