FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y tzdata && \
    apt-get upgrade -y && \
    apt-get install -y git
RUN apt-get install npm -y
RUN cd ~
RUN git clone https://github.com/cosmicjs/nodejs-chat-app.git
WORKDIR nodejs-chat-app
RUN npm install