FROM ubuntu:latest

RUN ln -snf /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && echo Europe/Warsaw > /etc/timezone

RUN apt-get -y update
RUN apt-get -y install git 
RUN apt-get -y install npm

RUN git clone https://github.com/feathersjs/feathers-chat
WORKDIR feathers-chat
RUN npm install

CMD [ "npm", "start" ]
