FROM alpine:3.4

RUN apt-get update 
RUN apk t install -y --no-install-recommends git

RUN git clone https://github.com/deltachat/deltachat-desktop.git
WORKDIR ./deltachat-desktop
RUN npm install 
RUN npm run build 
