FROM ubuntu:latest
ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update
RUN apt-get install git -y
RUN apt-get install npm -y
RUN git clone https://github.com/binhxn/node-chat-app
WORKDIR node-chat-app
RUN npm install
