FROM node:14.16.0-buster

RUN apt-get update
RUN apt-get install -y --no-install-recommends git make python g++ yarn


RUN git clone https://github.com/binhxn/node-chat-app.git
WORKDIR ./node-chat-app
RUN npm install


CMD ["npm", "start"]

