FROM node:10

RUN apt-get update && apt-get upgrade -y

RUN apt-get install python make g++ git
RUN git clone https://github.com/wireapp/wire-desktop.git

WORKDIR ./wire-desktop

RUN npm install 
CMD ["npm", "start"]
