FROM node:15.13.0-buster

#Instalacja niezbednych pakietów z repozytorium
RUN apt-get update && apt-get install -y --no-install-recommends git gcc g++ make python wget ca-certificates

#Utworzenie folderu i pobranie certyfikatów
RUN mkdir /usr/local/share/ca-certificates/cacert.org
RUN wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt  
RUN update-ca-certificates

#Aktualizacja programów
RUN apt-get update -y && apt-get dist-upgrade -y

#Aktualizacja npm
Run npm install -g npm@7.9.0

#Pobranie i kompilacja komunikatora z Github'a
RUN git clone https://github.com/deltachat/deltachat-desktop.git
WORKDIR ./deltachat-desktop
RUN npm install
RUN npm run build
