FROM node:14.15.1-buster

RUN apt-get update
RUN apt-get install -y --no-install-recommends git

RUN git clone https://github.com/BuiDuyThanh/node-chat-app
WORKDIR ./node-chat-app
RUN npm install -g nodemon
RUN npm install
ENTRYPOINT npm start
