FROM node:14.16.1-buster

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install git -y
RUN apt-get -y install npm

RUN git clone https://github.com/deltachat/deltachat-desktop.git
WORKDIR ./deltachat-desktop
RUN npm install
RUN npm run build
