# The latest version of Ubuntu is used as the base image for this Dockerfile.
FROM ubuntu:latest

RUN \ 
    apt-get update && \
    apt-get install -y git && \
    apt-get install -y build-essential 

