FROM ubuntu:latest
	RUN apt-get update
	RUN apt-get -y upgrade
	RUN apt-get install -y build-essential
	RUN apt-get install -y git
	RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MIFT2021.git
