FROM node:latest

WORKDIR /data

RUN apt-get -y install sudo

RUN git clone https://github.com/binhxn/node-chat-app.git /data/app

WORKDIR /data/app

RUN npm install

EXPOSE 3000

CMD ["npm", "start"]
