FROM ubuntu:latest

ENV TZ=Europe/Warsaw

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get -y install curl
RUN apt-get -y install git
RUN curl https://install.meteor.com/ | sh

RUN git clone https://github.com/RocketChat/Rocket.Chat.git
WORKDIR Rocket.Chat


RUN apt-get -y install nodejs
RUN apt-get -y install npm
RUN meteor npm install
RUN npm audit fix
RUN meteor npm start
