FROM node:14.16.0-buster

#ENV TZ=Europe/Warsaw

#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get -y install git

RUN git clone https://github.com/deltachat/deltachat-desktop.git
WORKDIR ./deltachat-desktop

RUN rm -rf node_modules package-lock.json
RUN npm install
RUN npm run build