
FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install git -y
RUN cd ~
RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MIFT2021
RUN cd MIFT2021; git checkout Grupa05-JS283683_Lab03